language: cpp
compiler:
  - clang
notifications:
  email: false
env:
  matrix:
    - JULIAVERSION="juliareleases"
    - JULIAVERSION="julianightlies"
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/${JULIAVERSION} -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libpcre3-dev julia -y
script:
  - julia -e 'Pkg.init(); run(`ln -s $(pwd()) $(Pkg.dir("Convex"))`); Pkg.pin("Convex"); Pkg.resolve()'
  - julia -e 'using Convex; @assert isdefined(:Convex); @assert typeof(Convex) === Module'
  - if [ $JULIAVERSION = "julianightlies" ]; then julia --code-coverage test/run_tests.jl; fi
  - if [ $JULIAVERSION = "juliareleases" ]; then julia test/run_tests.jl; fi
after_success:
  - julia -e 'cd(Pkg.dir("Convex")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'

