language: cpp
compiler:
  - clang
notifications:
  email: false
env:
  matrix:
    - JULIAVERSION="juliareleases"
    - JULIAVERSION="julianightlies"
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/${JULIAVERSION} -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libpcre3-dev julia -y
script:
  - julia -e 'Pkg.clone("git@github.com:karanveerm/ECOS.jl.git"); Pkg.build("ECOS");'
  - julia -e 'Pkg.init(); run(`ln -s $(pwd()) $(Pkg.dir("Convex"))`); Pkg.pin("Convex"); Pkg.resolve()'
  - julia -e 'using Convex; @assert isdefined(:Convex); @assert typeof(Convex) === Module'
  - julia -e 'using Convex; include("$(Pkg.dir("Convex"))/test/test.jl");'
